COMMAND_NAME="manual-failover"
COMMAND_TYPE="local-script"
COMMAND_PAYLOAD="/opt/adxc/bin/adxc-miqm-control manual-failover MQ_MIQM_EXAMPLE"
COMMAND_DESCRIPTION="Controlled failover from active to standby"
COMMAND_ENABLED="YES"
COMMAND_MENU="Control"
COMMAND_GROUP="Node Control"
