COMMAND_NAME="start-node"
COMMAND_TYPE="local-script"
COMMAND_PAYLOAD="/opt/adxc/bin/adxc-miqm-control start-node MQ_MIQM_EXAMPLE"
COMMAND_DESCRIPTION="Start local instance with standby permitted"
COMMAND_ENABLED="YES"
COMMAND_MENU="Control"
COMMAND_GROUP="Node Control"
