PROFILE_NAME="TQM1"
PROFILE_TEMPLATE="mq_miqm"
PROFILE_DESCRIPTION="IBM MQ Multi-Instance Queue Manager"
PROFILE_ENABLED="YES"
QMGR_NAME="TQM1"
PRIMARY_NODE="lxmqs04t"
SECONDARY_NODE="lxmqs05t"
MQMIQM_CONF="/etc/mqmiqm/cluster.conf"
