#!/usr/bin/env bash
# DESC: Show MIQM profile summary
# ==============================================================================

profile_dir=$(cd "$(dirname "$0")/.." && pwd)
# shellcheck source=/dev/null
. "$profile_dir/profile.conf"

echo "MIQM SUMMARY"
echo "Queue Manager : $QMGR_NAME"
echo "Primary Node  : $PRIMARY_NODE"
echo "Secondary Node: $SECONDARY_NODE"
