PROFILE_NAME="MQ_MIQM_EXAMPLE"
PROFILE_CLASS="MIQM"
PROFILE_TEMPLATE="mq_miqm"
PROFILE_DESCRIPTION="Example IBM MQ Multi-Instance profile"
PROFILE_ENABLED="YES"
PROFILE_STATUS="ACTIVE"
PROFILE_CREATED_BY="package"
PROFILE_CREATED_DATE="2026-07-21 13:34:00"
PROFILE_ARCHIVED_BY=""
PROFILE_ARCHIVED_DATE=""
