PROFILE_NAME="MQ_MIQM_EXAMPLE"
PROFILE_TEMPLATE="mq_miqm"
PROFILE_DESCRIPTION="Blank example IBM MQ Multi-Instance profile"
PROFILE_ENABLED="YES"
QMGR_NAME="QM_EXAMPLE"
PRIMARY_NODE="primary-node"
SECONDARY_NODE="secondary-node"
SHARED_FS_PATH="/shared/mqha"
MQMIQM_CONF="/etc/mqmiqm/cluster.conf"
CUSTOM_HEALTHCHECK=""
