COMMAND_NAME="stop-node"
COMMAND_TYPE="local-script"
COMMAND_PAYLOAD="/opt/adxc/bin/adxc-miqm-control stop-node TQM1"
COMMAND_DESCRIPTION="MQ MIQM command"
COMMAND_ENABLED="YES"
COMMAND_MENU="Control"
