PROFILE_NAME="MQ_STANDALONE_EXAMPLE"
PROFILE_CLASS="STANDALONE"
PROFILE_TEMPLATE="mq_standalone"
PROFILE_DESCRIPTION="Example IBM MQ Standalone profile"
PROFILE_ENABLED="YES"
PROFILE_STATUS="ACTIVE"
PROFILE_CREATED_BY="package"
PROFILE_CREATED_DATE="2026-07-21 13:34:00"
PROFILE_ARCHIVED_BY=""
PROFILE_ARCHIVED_DATE=""
