# -----------------------------------------------------------------------------
# aDXC-GAMA global configuration
# -----------------------------------------------------------------------------
ADXC_PRODUCT_NAME="aDXC-GAMA"
ADXC_VERSION="0.3.0-rc6"
ADXC_PROFILES_DIR_NAME="profiles"
ADXC_TEMPLATES_DIR_NAME="templates"
ADXC_ARCHIVE_PROFILES_DIR_NAME="archive/profiles"
ADXC_ARCHIVE_COMMANDS_DIR_NAME="archive/commands"
ADXC_COMMANDS_DIR_NAME="commands"
ADXC_SCRIPTS_DIR_NAME="scripts"
ADXC_COLOR_ENABLED="YES"
