PROFILE_NAME="GENERIC_MW_EXAMPLE"
PROFILE_TEMPLATE="generic_middleware"
PROFILE_DESCRIPTION="Blank example middleware product profile"
PROFILE_ENABLED="YES"
PRODUCT_NAME="GENERIC_MIDDLEWARE"
INSTANCE_NAME="INSTANCE_EXAMPLE"
