PROFILE_NAME="GENERIC_MW_EXAMPLE"
PROFILE_CLASS="GENERIC_MW"
PROFILE_TEMPLATE="generic_middleware"
PROFILE_DESCRIPTION="Example generic middleware profile"
PROFILE_ENABLED="YES"
PROFILE_STATUS="ACTIVE"
PROFILE_CREATED_BY="package"
PROFILE_CREATED_DATE="2026-07-21 13:34:00"
PROFILE_ARCHIVED_BY=""
PROFILE_ARCHIVED_DATE=""
