COMMAND_NAME="readiness-check"
COMMAND_TYPE="local-script"
COMMAND_PAYLOAD="/opt/adxc/bin/adxc-miqm-control readiness-check TQM2"
COMMAND_DESCRIPTION="MQ MIQM command"
COMMAND_ENABLED="YES"
COMMAND_MENU="Control"
