#!/usr/bin/env bash
ADXC_HOME=${ADXC_HOME:-/opt/adxc}
[ -r "$ADXC_HOME/lib/adxc-colors.sh" ] && . "$ADXC_HOME/lib/adxc-colors.sh"
adxc_version(){ [ -r "$ADXC_HOME/VERSION" ] && cat "$ADXC_HOME/VERSION" || echo unknown; }
adxc_today(){ date +%F; }
adxc_require_runtime(){ [ -n "${ADXC_RUNTIME:-}" ] && [ -d "$ADXC_RUNTIME" ] || { adxc_error "aDXC runtime is not active. Run: source ~/.adxc/activate.sh"; exit 1; }; }
adxc_load_user_config(){ adxc_require_runtime; [ -r "$ADXC_RUNTIME/config/user.conf" ] && . "$ADXC_RUNTIME/config/user.conf"; ADXC_ROLE=${ADXC_ROLE:-support}; ADXC_ACTIVE_PROFILES=${ADXC_ACTIVE_PROFILES:-}; }
adxc_profile_allowed(){ p="$1"; case "${ADXC_ROLE:-support}" in admin|ADMIN|root) return 0;; esac; case " ${ADXC_ACTIVE_PROFILES:-} " in *" $p "*) return 0;; *) return 1;; esac; }
adxc_profile_field(){ file="$1"; key="$2"; def="$3"; [ -r "$file" ] || { echo "$def"; return; }; awk -F= -v k="$key" -v d="$def" '$1==k{gsub(/^"|"$/, "", $2); print $2; found=1; exit} END{if(!found) print d}' "$file"; }
adxc_message_field(){ file="$1"; key="$2"; def="$3"; [ -r "$file" ] || { echo "$def"; return; }; awk -F= -v k="$key" -v d="$def" '$1==k{v=$0; sub(/^[^=]*=/,"",v); gsub(/^"|"$/, "", v); print v; found=1; exit} END{if(!found) print d}' "$file"; }
adxc_message_text(){ file="$1"; awk 'BEGIN{intext=0} /^TEXT<<ADXC_EOF$/{intext=1; next} /^ADXC_EOF$/{intext=0; next} intext{print}' "$file"; }
adxc_message_active(){ file="$1"; exp=$(adxc_message_field "$file" EXPIRES "9999-12-31"); today=$(adxc_today); [ "$exp" \> "$today" ] || [ "$exp" = "$today" ]; }
adxc_active_message_count(){ c=0; for f in "$ADXC_HOME/messages"/*.msg; do [ -f "$f" ] || continue; adxc_message_active "$f" && c=$((c+1)); done; echo "$c"; }
adxc_next_message_id(){ max=0; for f in "$ADXC_HOME/messages"/*.msg; do [ -f "$f" ] || continue; b=$(basename "$f" .msg); case "$b" in *[!0-9]*|'') continue;; esac; [ "$b" -gt "$max" ] && max="$b"; done; printf '%03d\n' $((max+1)); }
adxc_render_message_board(){ count=$(adxc_active_message_count); adxc_section "MESSAGE BOARD ($count)"; if [ "$count" -eq 0 ]; then printf '%b\n' "${ADXC_DIM} No active announcements.${ADXC_RESET}"; return; fi; first=1; for f in $(ls "$ADXC_HOME/messages"/*.msg 2>/dev/null | sort); do [ -f "$f" ] || continue; adxc_message_active "$f" || continue; [ "$first" -eq 1 ] || adxc_sep; first=0; type=$(adxc_message_field "$f" TYPE INFO); title=$(adxc_message_field "$f" TITLE "Untitled message"); exp=$(adxc_message_field "$f" EXPIRES "9999-12-31"); color=$(adxc_label_color "$type"); printf '%b[%s]%b\n' "$color" "$type" "$ADXC_RESET"; printf '%b\n\n' "$title"; adxc_message_text "$f"; printf '\nExpires : %s\n' "$exp"; done; }
adxc_list_profiles_compact(){ found=0; id=1; printf ' ID   Object      Description                         Access\n'; printf ' ---  ----------  ----------------------------------  --------\n'; printf ' [%s]  %-10s %-34s %s\n\n' 1 OS "Linux health checks and diagnostics" system; id=2; for d in "$ADXC_HOME/profiles"/*; do [ -d "$d" ] || continue; found=1; p=$(basename "$d"); conf="$d/profile.conf"; desc=$(adxc_profile_field "$conf" PROFILE_DESCRIPTION "Operational profile"); type=$(adxc_profile_field "$conf" PROFILE_TYPE custom); adxc_profile_allowed "$p" && access=allowed || access=inventory; printf ' [%s]  %-10s %-34s %s/%s\n\n' "$id" "$p" "$desc" "$type" "$access"; id=$((id+1)); done; [ "$found" -eq 1 ] || printf '%b\n' "${ADXC_YELLOW} No operational profiles configured yet.${ADXC_RESET}"; }
